### ISSUE TITLE
Update Jenkins and Nexus To Display As Applications in OCP

### ISSUE THREAD

**Issue by sherl0cks** [rht-labs/labs-ci-cd#10]
Like Sonar does
![screenshot from 2017-09-26 14-09-35](https://user-images.githubusercontent.com/1335137/30881873-70acd5d0-a2c4-11e7-873a-511efd8bb9aa.png)

**Comment by InfoSec812** [comment]
This used to work in OCP 3.5 and I am not sure why it is not showing up that way anymore. Suggestions?

**Comment by InfoSec812** [comment]
I found the answer. I need to add some metadata to the templates:

```

  labels:
    app: openshift-sonarqube
    appName: sonarqube
    name: openshift-sonarqube
```
